[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "achromatcfw"
version = "0.1.0"
description = "Achromat CFW utility package"
readme = ""
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["achromatcfw"]
